name: Sharp-API Docker Build and Push

on:
  push:
    tags:
      - 'js-sharp-api-*'

jobs:
  build-and-push:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux/amd64
          - os: ubuntu-24.04-arm
            platform: linux/arm64
    outputs:
      version: ${{ steps.version.outputs.version-number }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v6

      - name: Check out Sharp-API repo
        uses: actions/checkout@v6
        with:
          repository: 'carry0987/Sharp-API'
          token: ${{ secrets.GH_CLONE_TOKEN }}
          path: 'JS/Sharp-API/source'

      - name: Extract version from tag
        uses: carry0987/version-extractor@v1
        id: version
        with:
          tag: ${{ github.ref_name }}
          extract-pattern: 'js-sharp-api-(.*)'

      - name: Login to DockerHub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push by digest
        uses: carry0987/docker-digest-builder@v1
        with:
          image: ${{ secrets.DOCKER_USERNAME }}/sharp-api
          platform: ${{ matrix.platform }}
          context: JS/Sharp-API
          file: JS/Sharp-API/Dockerfile
          sbom: true

      - name: Logout from DockerHub
        if: always()
        run: docker logout

  manifest:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Create and push manifest
        uses: carry0987/docker-multi-arch-manifest@v1
        with:
          image: ${{ secrets.DOCKER_USERNAME }}/sharp-api
          tags: |
            ${{ needs.build-and-push.outputs.version }}
            latest

      - name: Logout from DockerHub
        if: always()
        run: docker logout
