name: PHP-FPM Docker Build and Push

on:
  push:
    tags:
      - 'php-fpm-[^alpine]*'

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Prepare the Docker tag
        id: prep
        run: |
          VERSION=$(echo ${{ github.ref }} | sed -e 's,.*/php-fpm-,,')
          echo "VERSION=${VERSION%*-latest}" >> $GITHUB_ENV
          if [[ "$VERSION" == *"-latest" ]]; then
            echo "LATEST_TAG=latest" >> $GITHUB_ENV
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./PHP/FPM
          file: ./PHP/FPM/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/php:${{ env.VERSION }}-fpm
            ${{ secrets.DOCKER_USERNAME }}/php:${{ env.LATEST_TAG }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7

      - name: Logout from DockerHub
        run: docker logout
