name: Docker Build and Push

on:
  push:
    tags:
      - 'php-fpm-*'

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract part of the tag for the Docker tag
        id: prep
        run: echo "##[set-output name=tag;]$(echo ${{ github.ref }} | sed -e 's,.*/php-fpm-,,')-fpm"

      - name: Build and push Docker image for PHP-FPM
        uses: docker/build-push-action@v5
        with:
          context: ./PHP/FPM
          file: ./PHP/FPM/Dockerfile
          push: true
          tags: ${{ steps.prep.outputs.tag }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7

      - name: Logout from DockerHub
        run: docker logout
