name: PHP-FPM Docker Build and Push

on:
  push:
    tags:
      - 'php-fpm-[^alpine]*'

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Prepare the Docker tags list and PHP version
        run: |
          FULL_VERSION=$(echo ${{ github.ref }} | sed -e 's,.*/php-fpm-,,')
          VERSION=${FULL_VERSION%-latest}
          TAGS="${{ secrets.DOCKER_USERNAME }}/php:${VERSION}-fpm"
          if [[ "$FULL_VERSION" == *"-latest" ]]; then
            TAGS="$TAGS,${{ secrets.DOCKER_USERNAME }}/php:latest"
          fi
          echo "TAGS=$TAGS" >> $GITHUB_ENV
          echo "PHP_VERSION=${VERSION%-fpm}" >> $GITHUB_ENV
          echo "PHP_VERSION=${VERSION%-fpm}"
          echo "Building with tags: $TAGS"

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./PHP/FPM
          file: ./PHP/FPM/Dockerfile
          build-args: PHP_VERSION=${{ env.PHP_VERSION }}
          push: true
          tags: ${{ env.TAGS }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7

      - name: Logout from DockerHub
        run: docker logout
